# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# manual mode
branches:
  except:
    - /.*/

# Do not build on tags (GitHub only)
skip_tags: true


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: https://www.appveyor.com/docs/windows-images-software/
os: Visual Studio 2022

environment:
  PROJECT_DIR: &PROJECT_DIR c:\project
  REPO_DIR:  c:\project\windows-chewing-tsf  # directory created by appveyor
  BUILD_DIR: c:\build
  INST_DIR:  c:\build\installer

  NSIS_EXE: c:\Program Files (x86)\NSIS\makensis.exe

  SQLITE_URL: https://www.sqlite.org/2024/sqlite-amalgamation-3450000.zip

  LIBCHEWING_TAG: v0.6.0

  CMAKE_GEN_X86: -G "Visual Studio 17 2022" -A "Win32"
  CMAKE_GEN_X64: -G "Visual Studio 17 2022" -A "x64"

  SOL_FILE: windows-chewing-tsf.sln
  MSBUILD_CMD_X86: /maxcpucount /property:Configuration=Release,Platform=Win32 /target:ChewingPreferences,ChewingTextService,all_static_data,data
  MSBUILD_CMD_X64: /maxcpucount /property:Configuration=Release,Platform=x64 /target:ChewingTextService

# clone directory
clone_folder: *PROJECT_DIR

# set clone depth
clone_depth: 1


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  # git submodules
  - 'cd "%REPO_DIR%"'
  - 'git submodule update --init --remote --recursive'
  - 'git -C libchewing checkout %LIBCHEWING_TAG%'

  # updating sqlite-amalgamation
  - 'cd \'
  - 'appveyor DownloadFile "%SQLITE_URL%" -FileName "sqlite.zip"'
  - '7z e -y "sqlite.zip" -o"%REPO_DIR%\libchewing\thirdparty\sqlite-amalgamation"'

# to run your custom scripts instead of automatic MSBuild
build_script:
  # build start
  - 'mkdir "%BUILD_DIR%"'

  # build x86
  - 'cd "%BUILD_DIR%" && mkdir "x86" && cd "x86"'
  - 'cmake %CMAKE_GEN_X86% "%REPO_DIR%"'
  - 'msbuild %SOL_FILE% %MSBUILD_CMD_X86%'

  # build x64
  - 'cd "%BUILD_DIR%" && mkdir "x64" && cd "x64"'
  - 'cmake %CMAKE_GEN_X64% "%REPO_DIR%"'
  - 'msbuild %SOL_FILE% %MSBUILD_CMD_X64%'

# scripts to run before deployment
after_build:
  # prepare for NSIS
  - 'mkdir "%INST_DIR%" && cd "%INST_DIR%"'
  - 'copy "%REPO_DIR%\installer\*" ".\"'
  - 'copy "%REPO_DIR%\COPYING.txt" ".\..\"'  # special case for LICENSE file

  - 'cd "%INST_DIR%" && mkdir "Dictionary"'
  - 'copy "%BUILD_DIR%\x86\libchewing\data\*.dat" ".\Dictionary"'
  - 'copy "%BUILD_DIR%\x86\libchewing\data\*.tab" ".\Dictionary"'

  - 'cd "%INST_DIR%" && mkdir "x86"'
  - 'copy "%BUILD_DIR%\x86\ChewingTextService\Release\*.dll" ".\x86"'
  - 'copy "%BUILD_DIR%\x86\libchewing\Release\*.dll" ".\x86"'
  - 'copy "%BUILD_DIR%\x86\ChewingPreferences\Release\*.exe" "."'

  - 'cd "%INST_DIR%" && mkdir "x64"'
  - 'copy "%BUILD_DIR%\x64\libchewing\Release\*.dll" ".\x64"'
  - 'copy "%BUILD_DIR%\x64\ChewingTextService\Release\*.dll" ".\x64"'

  # run NSIS
  - 'cd "%INST_DIR%"'
  - '"%NSIS_EXE%" "installer.nsi"'

  # prepare for artifacts packaging
  - 'cd "%INST_DIR%"'
  - 'copy "windows-chewing-tsf.exe" "%PROJECT_DIR%"'  # the artifact must reside at the source repo root

  # generate hash
  - 'cd "%PROJECT_DIR%"'
  - 'powershell -Command "& { $hash = (Get-FileHash -Algorithm SHA256 "windows-chewing-tsf.exe").hash.ToString().toLower(); Write-Host $hash " *windows-chewing-tsf.exe"; }" > "windows-chewing-tsf.exe.sha256"'


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: windows-chewing-tsf.exe
    name: installer
  - path: windows-chewing-tsf.exe.sha256
    name: checksum
